"""empty message

Revision ID: 442fdb5b0154
Revises: 
Create Date: 2021-09-02 14:22:52.214315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442fdb5b0154'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_details',
    sa.Column('book_name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('published_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('book_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_details')
    # ### end Alembic commands ###
